name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pacman
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Pacman
        uses: vitorjohnny/pacman-contribution-graph@v1.0.0
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          output-path: "output"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update pacman contribution graph"
